Baazar horizontal items
orden-gg/fireball pull request #173
Opened 2022-01-27 18:22 UTC by an-uhryn

2022-03-25 07:15 UTC, dudendy requested changes

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/common/HorizontalLink/styles.js
> +
please remove all empty lines between css properties

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/Wearable/styles.js
> +
please remove all empty lines between css properties

2022-03-25 07:15 UTC, dudendy commented on src/components/Gotchi/GotchiHorizontal.js
> +
please format functions same as in `<Gotchi>` component

```
funcitonName(prop) {
    return (
        content
    );
},
```

2022-03-25 07:15 UTC, dudendy commented on src/components/Gotchi/common/GotchiCollateral.js
> +        <Tooltip title={collateral} classes={{ tooltip: classes.customTooltip }} enterTouchDelay={0} placement='top' followCursor>
let's avoid long code like this and split props one by line

2022-03-25 07:15 UTC, dudendy commented on src/components/Gotchi/common/GotchiId.js
> +        <Tooltip title={`Haunt ${gotchi.hauntId}`} classes={{ tooltip: classes.customTooltip }} enterTouchDelay={0} placement='top' followCursor>
let's avoid long code like this and split props one by line

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/Portal/PortalHorizontal.js
> +
please format functions same as in `<Gotchi>` component

```
funcitonName(prop) {
    return (
        content
    );
},
```

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/Ticket/TicketHorizontal.js
> +
please format functions same as in `<Gotchi>` component

```
funcitonName(prop) {
    return (
        content
    );
},
```

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/Wearable/WearableHorizontal.js
> +
please format functions same as in `<Gotchi>` component

```
funcitonName(prop) {
    return (
        content
    );
},
```

2022-03-25 07:15 UTC, dudendy commented on src/components/Gotchi/styles.js
> +
please remove all empty lines between css properties

2022-03-25 07:15 UTC, dudendy commented on src/components/Items/common/HorizontalPrice/styles.js
> +
please remove all empty lines between css properties

2022-03-25 07:20 UTC, dmutrokot requested changes

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/Gotchi.js
> +                    value[key].map( item => (
extra space before `item`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +        if (typeof value === 'string') return gotchiSections[value];
please wrap `return` statement into `{}`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +            Object.keys(value).map( (key) => (
extra space before `key`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +                gotchiSections[key](value[key].map( item => (
extra space before `item`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/GotchiHorizontal.js
> +            {render.map( (name) => {
extra space before `name`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/common/GotchiBadges.js
> +import styles from '../styles';
please separate

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/common/GotchiMainTraits.js
> +                                    ({gotchi.baseRarityScore})
please format

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/common/GotchiRewards.js
> +                                        <p key={index}>
please avoid using index as a `key` if possible

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Gotchi/styles.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +        if (typeof value === 'string') return gotchiSections[value];
please wrap `return` into `{}`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +            Object.keys(value).map( (key) => (
extra space before `key`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +                gotchiSections[key](value[key].map( item => (
extra space before `item`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalHorizontal.js
> +            {render.map( (name) => {
extra space before `name `

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Portal/PortalImage.js
> +        } alt='Portal' />
please format

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +                                  itemRarity={itemUtils.getItemRarityName(ticket.erc1155TypeId)} item={ticket} />
please put props from newline

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +        if (typeof value === 'string') return gotchiSections[value];
please wrap `return` into `{}`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +            Object.keys(value).map( (key) => (
extra space before `key`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +                gotchiSections[key](value[key].map( item => (
extra space before `item`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Ticket/TicketHorizontal.js
> +            {render.map( (name) => {
extra space before `name`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +import itemUtils from 'utils/itemUtils';
it should goes first in this case in imports statements, as it's absolute path and above imports are relative

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +        if (typeof value === 'string') return gotchiSections[value];
please wrap `return` into `{}`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +            Object.keys(value).map( (key) => (
extra space before `key`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +                gotchiSections[key](value[key].map( item => (
extra space before `item`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/Wearable/WearableHorizontal.js
> +            {render.map( (name) => {
extra space before `name`

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/common/CardName/CardName.js
> +import classNames from 'classnames';
please separate from core imports as it is third party

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/styles.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/styles.js
> +        // alignItems: 'center',
please remove if not needed

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/styles.js
> +        // alignItems: 'center',
please remove if not needed

2022-03-25 07:20 UTC, dmutrokot commented on src/components/Items/styles.js
> +        // alignItems: 'center',
please remove if not needed

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSidebar/styles.js
> +        // position: 'sticky',
please remove if not needed

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +import classNames from 'classnames';
should be separated to third party imports

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +                            return <div key={index} className={classes.baazaarListItem}>
please avoid setting `key` as `index` if possible

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +                                {/*{*/}
please remove if not needed

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +                            return <div key={index} className={classes.baazaarListItem}>
please avoid set `index` to `key` if possible

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +
extra whitespace

2022-03-25 07:20 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.js
> +                    goods.length ? <Pagination
please move `Pagination` onto new line

2022-03-25 10:56 UTC, Vladislav94 commented on src/pages/Baazaar/components/BaazaarSidebar/styles.js
> +        // top: 94,
fixed

2022-03-25 11:00 UTC, Vladislav94 commented on src/components/Items/common/HorizontalLink/styles.js
> +
done

2022-03-25 11:00 UTC, Vladislav94 commented on src/components/Items/Wearable/styles.js
> +
done

2022-03-25 11:29 UTC, Vladislav94 commented on src/components/Gotchi/common/GotchiCollateral.js
> +        <Tooltip title={collateral} classes={{ tooltip: classes.customTooltip }} enterTouchDelay={0} placement='top' followCursor>
done

2022-03-25 11:35 UTC, Vladislav94 commented on src/components/Items/Portal/PortalHorizontal.js
> +
done

2022-03-25 11:35 UTC, Vladislav94 commented on src/components/Items/Ticket/TicketHorizontal.js
> +
done

2022-03-25 11:35 UTC, Vladislav94 commented on src/components/Items/Wearable/WearableHorizontal.js
> +
done

2022-03-25 12:06 UTC, Vladislav94 commented on src/components/Gotchi/styles.js
> +
done

2022-03-25 12:06 UTC, Vladislav94 commented on src/components/Items/common/HorizontalPrice/styles.js
> +
done

2022-03-25 12:12 UTC, Vladislav94 commented on src/components/Gotchi/Gotchi.js
> +                    value[key].map( item => (
done

2022-03-25 12:15 UTC, Vladislav94 commented on src/components/Gotchi/GotchiHorizontal.js
> +
done

2022-03-25 12:15 UTC, Vladislav94 commented on src/components/Gotchi/GotchiHorizontal.js
> +
done

2022-03-25 12:16 UTC, Vladislav94 commented on src/components/Gotchi/GotchiHorizontal.js
> +
done

2022-03-28 07:58 UTC, dudendy approved these changes

2022-03-28 07:59 UTC, merged