feat: cost of wearable sets
orden-gg/fireball pull request #194
Opened 2022-02-14 13:00 UTC by knyumatt

2022-02-15 05:53 UTC, andkoval requested changes
@knyumatt first of all awesome work, thanks for your contribution.

1. Looks simple and good for me
2. Some issues with price formatting occurring in wearables cards
3. Sets BRS, Traits
4. I would add it in `/market` sidebar for now, there are some plans to improve market routing since rn it's only 1 page with all data coming at once.

I think we can publish this page after this checklist:

- [ ] add link to `/market` sidebar
- [ ] fix wearable cards price formatting issue
- [ ] add ability to navigate to available baazaar listing for each item

**Do you have the desire to do these adjustments by yourself? Or should we take care of it?**

2022-02-15 05:53 UTC, andkoval commented on src/components/Items/ERC1155/ERC1155.js
> +                                                : parseFloat(web3.utils.fromWei(item.priceInWei))))
need to review this price formatting horror :)
it breaks in some other places.
<img width="1434" alt="Screenshot 2022-02-15 at 12 23 39" src="https://user-images.githubusercontent.com/42136738/153998011-b78391f5-6c3d-4b0a-91e5-384ef778c416.png">

2022-02-15 14:54 UTC, knyumatt commented on src/components/Items/ERC1155/ERC1155.js
> +                                                : parseFloat(web3.utils.fromWei(item.priceInWei))))
I will address this issue first. Sorry that I am not familiar with the code base

2022-02-15 15:33 UTC, knyumatt commented
@andkoval Thank you for reviewing. 
The last commit has addressed the formatting and the route.

For 
- [ ] add link to `/market` sidebar
- [ ] add ability to navigate to available baazaar listing for each item
, I am not sure about the expectation. Perhaps you guys can handle it better than me.

2022-03-14 04:11 UTC, dudendy commented
@knyumatt sorry I missed your answer somehow. Thanks for your work, we will finish this page.

2022-06-21 17:28 UTC, closed without merging