fix issue
orden-gg/fireball pull request #249
Opened 2022-04-06 07:56 UTC by Vladislav94

2022-04-06 20:49 UTC, dmutrokot requested changes

2022-04-06 20:49 UTC, dmutrokot commented on src/api/ghst.api.js
> +        ))
semicolon missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +        if(!ghstApproved) {
space missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +                if(!approval) {
space missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +                    checkGhstSpend()
semicolon missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +                showSnackbar('error', errorMessage)
semicolon missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +            setStakeState('approve')
semicolon missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +                return {...data}
semicolon missed

2022-04-06 20:49 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +            })
semicolon missed

2022-04-06 20:51 UTC, dmutrokot commented on src/pages/Autopet/AutopetContextProvider.js
> +            };
no semicolon needed

2022-04-07 05:11 UTC, dudendy approved these changes

2022-04-07 05:12 UTC, merged