Client updates + lendings
orden-gg/fireball pull request #251
Opened 2022-04-08 14:57 UTC by dudendy

2022-04-08 19:58 UTC, dmutrokot requested changes

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Filters/LazySorting.js
> +export default function LazySorting({ items, setItems, sortingList, setSorting, defaults, placeholder }) {
what is `defaults`? please give a proper name

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Filters/LazySorting.js
> +        setSorting([sorting, value]);
it is unclear for what purposes `sorting, value` stands for. As I've understood it is `sortType(sortProp)` and `sortDirection`. If I am not mistaken please rename this variables, and please rename also in `ClientContext` such things as: `const [gFilter, gDir] = gotchisSorting;` to for example: `const [gSortProp, gSortDir] = gotchisSorting;`. Related to all components that are using `LazySorting`. For consistency sake in the application

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Filters/LazySorting.js
>      const onDirectionChange = (event, value) => {
please consume `sorting` as an argument here, like `currentSortProp` or something like this and not use it from global scope. You can pass it here: ` onChange={(event, value) => onDirectionChange(event, value)}`

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/Gotchi.js
> -
classnames isn't related to react, please keep it separated

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +    const dayMillis = 86400 * 1000;
would be better to move `dayMillis` and `halfDayMillis` to some type of global constants, and supposedly there is no need to multiply by 1000, just set 86 400 000

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +            ) : DateTime.local() - lastActivity > halfDayMillis ? (
please wrap `DateTime.local() - lastActivity > halfDayMillis` into `()`, a little bit confusing statement

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +            DateTime.local() - lastActivity > dayMillis ? (
wrap it also please

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        <span className={gotchi.splitBorrower > 0 ? 'highlight' : undefined}>
please use logical AND instead of ternary

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        <span className={gotchi.splitOther > 0 ? 'highlight' : undefined}>
please use logical AND instead of ternary

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        title={<span>total <span className='highlight'>tokens</span> / balanced <span className='highlight'>income</span></span>}
please format a little bit:)

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                {gotchi.tokensToShare.map((token, index) => {
is there `gotchi.tokensToShare` always are going to be not an empty array? if this can be empty please add condition above for `<div className={classNames(classes.section, classes.tokens)}>` to not rendering an empty tag

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        title={<span>last claimed: <span className='highlight'>{lastClaimed > 0 ? lastClaimed.toRelative() : 'never'}</span></span>}
please format

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Gotchi/GotchiLendingStats/styles.js
> +        padding: '4px 0 0 ',
extra space

2022-04-08 19:58 UTC, dmutrokot commented on src/components/Lazy/ItemsLazy.js
> +        </NoContent>
missed semicolon

2022-04-08 19:58 UTC, dmutrokot commented on src/components/RealmSwitchButton/RealmSwitchButton.js
> +        let path = view === 'list' ? 'map' : 'list';
please use `const`

2022-04-08 19:58 UTC, dmutrokot commented on src/components/RealmSwitchButton/RealmSwitchButton.js
> +        let url = `${match.url}/${path}`;
please use `const`

2022-04-08 19:58 UTC, dmutrokot commented on src/contexts/ClientContext.js
> +    const [gotchisSorting, setGotchisSorting] = useState(['modifiedRarityScore', 'desc']);
I would prefer to use here an object instead of an array, we can discuss it

2022-04-08 19:58 UTC, dmutrokot commented on src/contexts/ClientContext.js
> +            .then(lendings => lendings)
it is redundant, please remove it. Name `lendings` instead of `response` on the very next line

2022-04-08 19:58 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealm.js
> +    const redirect = `${match.path}/${realmView}${params ? `?${qs.stringify(params)}` : ''}`;
`redirect` -> `redirectUrl`

2022-04-08 19:58 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
>  import fud from 'assets/images/icons/fud.png';
maybe better will be to use svg here?

2022-04-08 19:58 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +        icon: <img src={fomo} alt='Fud' width={18} />
wrong `alt`, please check others

2022-04-09 03:19 UTC, dudendy commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        <span className={gotchi.splitBorrower > 0 ? 'highlight' : undefined}>
Was done in this way to to prevent current warning
```index.js:1 Warning: Received `false` for a non-boolean attribute `className`.

If you want to write it to the DOM, pass a string instead: className="false" or className={value.toString()}.

If you used to conditionally omit it with className={condition && value}, pass className={condition ? value : undefined} instead.```

2022-04-09 03:20 UTC, dudendy commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        <span className={gotchi.splitOther > 0 ? 'highlight' : undefined}>
Was done in this way to prevent current warning
```
Warning: Received `false` for a non-boolean attribute `className`.

If you want to write it to the DOM, pass a string instead: className="false" or className={value.toString()}.

If you used to conditionally omit it with className={condition && value}, pass className={condition ? value : undefined} instead.
```

2022-04-09 03:22 UTC, dudendy commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        title={<span>total <span className='highlight'>tokens</span> / balanced <span className='highlight'>income</span></span>}
move it to the next line but don't want to separate for more lines to prevent adding additional classes for managing spaces

2022-04-09 03:35 UTC, dudendy commented on src/components/Lazy/ItemsLazy.js
> +        </NoContent>
nono, only if the return Component would be wrapped in `()`

2022-04-09 03:37 UTC, dudendy commented on src/pages/Client/routes/ClientRealmList.js
>  import fud from 'assets/images/icons/fud.png';
yes sir

2022-04-09 03:40 UTC, dudendy commented on src/pages/Client/routes/ClientRealmList.js
>  import fud from 'assets/images/icons/fud.png';
Icons component? need to discuss

2022-04-09 06:55 UTC, dudendy commented on src/pages/Client/routes/ClientRealmList.js
>  import fud from 'assets/images/icons/fud.png';
agreed 😉

2022-04-09 08:01 UTC, dmutrokot requested changes

2022-04-09 08:26 UTC, dudendy commented on src/components/Gotchi/GotchiLendingStats/GotchiLendingStats.js
> +                        <span className={gotchi.splitOwner > 0 ? 'highlight' : undefined}>
discussed

2022-04-09 08:36 UTC, dmutrokot approved these changes

2022-04-09 10:33 UTC, merged