Guilds UI
orden-gg/fireball pull request #252
Opened 2022-04-09 12:53 UTC by Vladislav94

2022-05-02 14:02 UTC, dmutrokot requested changes

2022-05-02 14:02 UTC, dmutrokot commented on src/pages/Guilds/routes/GuildsPreview.js
> +    // const setNumber = amount => {
please leave TODO

2022-05-03 14:05 UTC, dudendy requested changes

2022-05-03 14:05 UTC, dudendy commented on src/pages/Guilds/GuildsContext.js
> +        return () => mounted = true;
`mounted` means that component is initiated. 
I would suggest that we need a different approach without `return` statement inside promise (just if condition).

Same as we have in `BalancesContext.js`

2022-05-03 14:05 UTC, dudendy commented on src/pages/Guilds/components/GuildGotchis.js
> +import { GuildsContext } from '../GuildsContext';
separate `GuildsContext` from current imports (see imports order)

2022-05-03 14:05 UTC, dudendy commented on src/pages/Guilds/components/GuildGotchis.js
> +        return () => mounted = false;
same thing with `mounted` what I described above

2022-05-03 14:05 UTC, dudendy commented on src/pages/Guilds/components/GuildLendings.js
> +        return () => mounted = false;
"mounted" issue

2022-05-03 14:05 UTC, dudendy commented on src/pages/Guilds/routes/Guild.js
> +import commonUtils from 'utils/commonUtils';
check imports order please

2022-05-03 14:23 UTC, dmutrokot commented on src/components/Modal/Modal.js
> +export default function CustomModal({children, modalOpen, setModalOpen, className, handleModalClose}) {
fixed, thanks

2022-05-03 14:23 UTC, dmutrokot commented on src/components/Modal/Modal.js
> +            <Box className={classNames(classes.modal, className || null)} >
fixed, thanks

2022-05-03 14:23 UTC, dmutrokot commented on src/components/Modal/styles.js
> +
fixed, thanks

2022-05-03 14:23 UTC, dmutrokot commented on src/components/Modal/styles.js
> +
fixed, thanks

2022-05-03 14:23 UTC, dmutrokot commented on src/pages/Guilds/GuildsContext.js
> +        return () => mounted = true;
fixed, thanks

2022-05-03 14:23 UTC, dmutrokot commented on src/pages/Guilds/components/GuildGotchis.js
> +import { GuildsContext } from '../GuildsContext';
fixed, thanks

2022-05-03 14:24 UTC, dmutrokot commented on src/pages/Guilds/components/GuildLendings.js
> +        return () => mounted = false;
seems here it works as designed

2022-05-03 14:24 UTC, dmutrokot commented on src/pages/Guilds/routes/Guild.js
> +import commonUtils from 'utils/commonUtils';
fixed, thanks

2022-05-03 14:24 UTC, dmutrokot commented on src/pages/Guilds/components/GuildGotchis.js
> +        return () => mounted = false;
here works as designed

2022-05-03 14:24 UTC, dmutrokot commented on src/pages/Guilds/routes/GuildsPreview.js
>  import commonUtils from 'utils/commonUtils';
fixed, thanks

2022-05-03 14:34 UTC, dmutrokot approved these changes

2022-05-04 08:12 UTC, dudendy approved these changes

2022-05-04 08:12 UTC, merged