Feat: filter dropdown next to sorting
orden-gg/fireball pull request #276
Opened 2022-05-01 13:46 UTC by dmutrokot

2022-05-18 08:36 UTC, dmutrokot commented on src/components/Filters/components/InputFilter/InputFilter.js
> +    const onInputChange = useCallback((value) => {
fixed, thanks

2022-05-18 08:36 UTC, dmutrokot commented on src/components/Filters/components/MultiButtonSelectionFilter/MultiButtonSelectionFilter.js
> +                            className={classNames(classes.item, item.isSelected ? 'selected' : '' )}
fixed, thanks

2022-05-18 08:38 UTC, dmutrokot commented on src/components/Filters/components/MultiAutocompleteFilter/MultiAutocompleteFilter.js
> +            renderInput={(params) => (
fixed, thanks

2022-05-18 08:38 UTC, dmutrokot commented on src/components/Filters/components/RangeSliderFilter/RangeSliderFilter.js
> +import CustomTooltip from 'components/custom/CustomTooltip';
fixed, thanks

2022-05-18 08:38 UTC, dmutrokot commented on src/components/Filters/components/RangeSliderFilter/RangeSliderFilter.js
> +    const onSliderChangeCommited = useCallback((value) => {
fixed, thanks

2022-05-18 08:38 UTC, dmutrokot commented on src/components/Filters/components/RangeSliderFilter/RangeSliderFilter.js
> +                size={'small'}
fixed, thanks

2022-05-18 08:38 UTC, dmutrokot commented on src/components/Filters/components/SingleAutocompleteFilter/SingleAutocompleteFilter.js
> +            renderInput={(params) => (
fixed, thanks

2022-05-18 08:39 UTC, dmutrokot commented on src/pages/Client/routes/ClientGotchis.js
> +        return (isSortingChanged || isFiltersApplied) ? modifiedGotchis: gotchis;
added space, but left brackets for readability

2022-05-18 08:39 UTC, dmutrokot commented on src/pages/Client/routes/ClientLendings.js
> +        return (isSortingChanged || isFiltersApplied) ? modifiedLendings: lendings;
added space, but left brackets for readability

2022-05-18 08:39 UTC, dmutrokot commented on src/pages/GhostExplorer/GhostExplorer.js
> +        return (isSortingChanged || isFiltersApplied) ? modifiedGotchis: gotchis;
added space, but left brackets for readability

2022-05-18 08:40 UTC, dmutrokot commented on src/pages/Lend/Lend.js
> +        return (isSortingChanged || isFiltersApplied) ? modifiedLendings: lendings;
added space, but left brackets for readability

2022-05-18 08:40 UTC, dmutrokot commented on src/pages/Lend/Lend.js
>                  response.forEach((listing) => {
fixed, thanks

2022-05-18 08:40 UTC, dmutrokot commented on src/pages/Lend/Lend.js
> +                            {getLendings().map((lend) => {
fixed, thanks

2022-05-19 14:09 UTC, dudendy requested changes

2022-05-19 14:09 UTC, dudendy commented on src/components/SortFilterPanel/SortFilterPanel.js
> +            { itemsLength > 0 &&
let's be consistent and wrap component into `()`

2022-05-19 14:09 UTC, dudendy commented on src/components/SortFilterPanel/styles.js
> +
extra space

2022-05-19 14:09 UTC, dudendy commented on src/pages/Client/Client.js
> -
please add space

2022-05-21 05:03 UTC, dudendy approved these changes

2022-05-21 15:01 UTC, merged