Parcel page migration
orden-gg/fireball pull request #282
Opened 2022-05-17 15:19 UTC by dudendy

http://localhost:3005/parcel/46049

2022-05-17 15:34 UTC, dmutrokot requested changes

2022-05-17 15:34 UTC, dmutrokot commented on src/pages/Parcel/ParcelPage.js
> +                    setParcelLoading(false);
you could `setParcelLoading(false)` into `finally` callback

2022-05-17 15:34 UTC, dmutrokot commented on src/components/Previews/SalesHistory/SalesHistory.js
> +                    setHistoryLoading(false);
add `finally` handler and move setter there

2022-05-18 08:38 UTC, dudendy commented on src/components/Previews/SalesHistory/SalesHistory.js
> +                    setHistoryLoading(false);
will be handled in next update

2022-05-18 13:33 UTC, dmutrokot approved these changes

2022-05-18 13:41 UTC, merged