feat: Parcel card 2.0, client realm filters improvement
orden-gg/fireball pull request #292
Opened 2022-05-23 12:18 UTC by dudendy

2022-06-03 20:43 UTC, dmutrokot requested changes

2022-06-03 20:43 UTC, dmutrokot commented on src/api/installations.api.js
> +        console.log('ids', ids);
remove please

2022-06-03 20:43 UTC, dmutrokot commented on src/api/installations.api.js
> +        console.log('ids', ids);
also check other `console.log`s

2022-06-03 20:43 UTC, dmutrokot commented on src/components/ActiveListingButton/ActiveListingButton.js
> +                if(mounted && res) {
space missed. And why would you need `res` condition? `listing` can be null

2022-06-03 20:43 UTC, dmutrokot commented on src/components/CopyToClipboard/CopyToClipboardBlock.js
> +                {/* <ContentCopyIcon className={classes.blockIcon} /> */}
please remove

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/Parcel/Parcel.js
> +                        let key = boost[0];
please use `const`

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/Parcel/ParcelChanneling.js
> +        // realmApi.getParcelInfo(parcelId).then(res => {
please remove

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/Parcel/ParcelChanneling.js
> +
seems that is no need for it

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/Parcel/ParcelName.js
> +import classNames from 'classnames';
separate please

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/ParcelImage/ParcelImage.js
> +                cache[0] = []
semicolon missed, please also check formatting in other statements in `map`

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/ParcelImage/ParcelImage.js
> -        .finally(() => setImageLoading(false));
why would you remove `finally` here?

2022-06-03 20:43 UTC, dmutrokot commented on src/components/Items/ParcelInstallations/ParcelInstallations.js
> +                return <div className={classes.installation} key={index}>
please wrap into `()`

2022-06-03 20:43 UTC, dmutrokot commented on src/contexts/ClientContext.js
> +            .then(async (res) => {
no need for `async`

2022-06-03 20:43 UTC, dmutrokot commented on src/data/citadel.data.js
> +        // selected: 0xfd9af9,
please remove if not needed

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +
no need for whitespace

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +        const accounts = metaState.account;
is it possible to reuse logic from `LoginContext`?

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +        const succesMessage = `successefully finished ${ids.length} upgrades`;
`successefully` typo

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +        const errorMessage = 'upgrades finishing went wrong :(';
`upgrades finishing` maybe should be vice versa

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +                        Finishing <CircularProgress size={20} color='secondary' sx={{ marginLeft: '8px' }} />
do we prefer to use inline styles?

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +                sx={{ marginBottom: '8px' }}
do we prefer to use inline styles?

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/components/ClientRealmActions.js
> +                <Alert severity='error' sx={{ marginBottom: '8px' }}>
do we prefer to use inline styles?

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +                const parcelUpgrading = realmUpgradesQueue.find(upgrade => upgrade.parcelId === parcel.tokenId);
`parcelUpgrading` -> `isParcelUpgrading`

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +                    upgrading: parcelUpgrading ? parcelUpgrading : undefined,
can be simplified to `Boolean(parcelUpgrading)`

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +                .map((que, i) => ({ ...que, upgradeIndex: i })) // add indexes (needed for onUpgradesFinish function)
what is `que`?

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +                return upgradesWithTimestamps;
missed whitespace

2022-06-03 20:43 UTC, dmutrokot commented on src/pages/Client/routes/ClientRealmList.js
> +                    upgradesWithTimestamps.filter(que => que.ready).map(que => que.upgradeIndex)
still, what is `que` ?:)

2022-06-03 20:43 UTC, dmutrokot commented on src/utils/installationsUtils.js
> +        return installations[id][15];
to avoid potential bugs and unclarity  please create 'enum' for such magic numbers

2022-06-03 20:43 UTC, dmutrokot commented on src/utils/installationsUtils.js
> +        return installations[id][15];
applies to all magic numbers in the file related to the installations

2022-06-04 09:25 UTC, dudendy commented on src/components/Items/ParcelImage/ParcelImage.js
> -        .finally(() => setImageLoading(false));
temporary we don't handle case when data not arrived

2022-06-04 09:27 UTC, dudendy commented on src/data/citadel.data.js
> +        // selected: 0xfd9af9,
parcel default colors needed for further theme implementation

2022-06-04 09:28 UTC, dudendy commented on src/pages/Client/components/ClientRealmActions.js
> +        const accounts = metaState.account;
not really, a bit different case
`LoginContext` - app login state
`metaState` - metamask login state

2022-06-04 09:32 UTC, dudendy commented on src/pages/Client/components/ClientRealmActions.js
> +                        Finishing <CircularProgress size={20} color='secondary' sx={{ marginLeft: '8px' }} />
in this case I would leave it here to not create separate styles file with 1 line of CSS rule

2022-06-04 09:33 UTC, dudendy commented on src/pages/Client/components/ClientRealmActions.js
> +                sx={{ marginBottom: '8px' }}
in this case I would leave it here to not create separate styles file with 2 line of CSS rule

2022-06-04 09:33 UTC, dudendy commented on src/pages/Client/components/ClientRealmActions.js
> +                <Alert severity='error' sx={{ marginBottom: '8px' }}>
in this case I would leave it here to not create separate styles file with 3 lines of CSS rule xD

2022-06-04 10:05 UTC, dudendy commented on src/pages/Client/components/ClientRealmActions.js
> +                <Alert severity='error' sx={{ marginBottom: '8px' }}>
okay okay let it be xd

2022-06-04 10:11 UTC, dudendy commented on src/pages/Client/routes/ClientRealmList.js
> +                .map((que, i) => ({ ...que, upgradeIndex: i })) // add indexes (needed for onUpgradesFinish function)
queue

2022-06-04 10:11 UTC, dudendy commented on src/pages/Client/routes/ClientRealmList.js
> +                    upgradesWithTimestamps.filter(que => que.ready).map(que => que.upgradeIndex)
queue

2022-06-04 10:52 UTC, dmutrokot requested changes

2022-06-04 10:52 UTC, dmutrokot commented on src/api/installations.api.js
> +                return [];
missed whitespace before `return`

2022-06-04 10:52 UTC, dmutrokot commented on src/api/installations.api.js
> +                return [];
missed whitespace before `return`

2022-06-04 10:52 UTC, dmutrokot commented on src/components/ActiveListingButton/ActiveListingButton.js
> +                    console.log(res)
please remove

2022-06-04 10:52 UTC, dmutrokot commented on src/components/Items/ParcelImage/ParcelImage.js
>              if (cache[cache.length -1].length < 4) {
missed space after -

2022-06-04 10:52 UTC, dmutrokot commented on src/components/Items/ParcelImage/ParcelImage.js
> +                cache[cache.length] = [item]
missed semicolon

2022-06-04 10:52 UTC, dmutrokot commented on src/data/types.js
> +    Name: 15,
no comma needed

2022-06-05 10:51 UTC, dmutrokot approved these changes

2022-06-08 10:49 UTC, merged