Craft page
orden-gg/fireball pull request #319
Opened 2022-06-23 15:27 UTC by Vladislav94

2022-06-28 13:29 UTC, dmutrokot requested changes

2022-06-28 13:32 UTC, dudendy requested changes

2022-06-28 13:32 UTC, dudendy commented on src/api/installations.api.ts
> +import { InstallationTypes, INSTALLATION_CONTRACT } from 'shared/constants';
`shared` imports should always go first in this section, related to all `shared` imports

2022-06-28 13:32 UTC, dudendy commented on src/api/installations.api.ts
> +        .catch(error => console.log('❌', error, '❌'));
let's don't use emojis here

2022-06-28 13:32 UTC, dudendy commented on src/data/scripts/tiles.script.js
> +import {  } from '../../api/common/constants.js';
please remove

2022-06-30 08:09 UTC, dmutrokot requested changes

2022-06-30 08:09 UTC, dmutrokot commented on src/pages/Craft/CraftContext.tsx
> +            ) || 0;
seems to be to complex expression. Please create separate variable for `...selectedItem.alchemicaCost.map((price, index) =>
                    Math.floor(tokens[index].amount / price)
                )`

2022-06-30 08:09 UTC, dmutrokot commented on src/pages/Craft/CraftContext.tsx
> +            setMaxCraftAmount(maxCraftAmount > 200 || isFreeItem ? 200 : maxCraftAmount);
please avoid passing such expressions to methods and create variable instead and the pass it

2022-06-30 08:09 UTC, dmutrokot commented on src/pages/Craft/components/ApproveModal.tsx
> +                    currentApprovals[category][activeIndex] = isApproved;
when we are modifying state cache, would be better to create cache copy variable that is deeply cloned with lodash to prevent some unpleasant bugs in the future

2022-06-30 08:09 UTC, dmutrokot commented on src/pages/Craft/components/Craftbar.tsx
>      const [craftAmount, setCraftAmount] = useState<any>(0);
is that couldn't be specifies as number?

2022-06-30 08:09 UTC, dmutrokot commented on src/pages/Craft/components/Craftbar.tsx
> +            const gltrs: any[] = Array(amount).fill(0);
seems to this type could be a `number[]`

2022-06-30 12:31 UTC, dmutrokot commented on src/components/Items/common/AlchemicaPrice/AlchemicaPrice.tsx
> +                            <span className={classes.amount}>{alchemica[index]}</span>
is there supposed to be `amount` instead of `{alchemica[index]}`?

2022-06-30 13:23 UTC, dmutrokot requested changes

2022-06-30 13:23 UTC, dmutrokot commented on src/components/Items/Tile.js/Tile.tsx
> +export function Tile({ tile, showPrice }: { tile: any, showPrice?: any }) {
`showPrice` is boolean

2022-06-30 13:23 UTC, dmutrokot commented on src/components/Items/common/AlchemicaPrice/AlchemicaPrice.tsx
> +import { TokensPricesContext } from 'contexts/TokensPricesContext';
contexts should go before utils

2022-06-30 13:23 UTC, dmutrokot commented on src/components/Items/common/AlchemicaPrice/AlchemicaPrice.tsx
> +    const classes = styles();
please add whitespace after `classes` for clarity

2022-06-30 13:23 UTC, dmutrokot commented on src/components/Items/common/AlchemicaPrice/AlchemicaPrice.tsx
> +            const price = getItemPrice();
as you triggering effect on `alchemica` change you can pass it to `getItemPrice` and do not wrap it into `useCallback`

2022-06-30 13:23 UTC, dmutrokot commented on src/components/Items/common/AlchemicaPrice/AlchemicaPrice.tsx
> +                    alchemica.map((amount: number, index: number ) => {
extra space

2022-06-30 13:23 UTC, dmutrokot commented on src/data/scripts/installations.script.ts
> +import { INSTALLATION_CONTRACT } from '../../shared/constants/api.constants.ts';
there is no need to specify `.ts` extension, please remove it and remove `@ts-ignore`

2022-06-30 13:23 UTC, dmutrokot commented on src/data/scripts/installations.script.ts
> +import { InstallationTypes } from '../../shared/constants/enums.ts';
there is no need to specify `.ts` extension, please remove it and remove `@ts-ignore`

2022-06-30 13:23 UTC, dmutrokot commented on src/data/scripts/installations.script.ts
> +    .then((res: any): void => {
no need to specify callbacks return type

2022-06-30 13:23 UTC, dmutrokot commented on src/data/scripts/tiles.script.ts
> +import { TILES_CONTRACT } from '../../shared/constants/api.constants.ts';
there is no need to specify `.ts` extension, please remove it and remove `@ts-ignore`

2022-06-30 13:37 UTC, dmutrokot commented on src/data/scripts/installations.script.ts
> +import { INSTALLATION_CONTRACT } from '../../shared/constants/api.constants.ts';
discussed

2022-06-30 13:37 UTC, dmutrokot commented on src/data/scripts/installations.script.ts
> +import { InstallationTypes } from '../../shared/constants/enums.ts';
discussed

2022-06-30 13:37 UTC, dmutrokot commented on src/data/scripts/tiles.script.ts
> +import { TILES_CONTRACT } from '../../shared/constants/api.constants.ts';
discussed

2022-06-30 13:38 UTC, dmutrokot commented on src/data/scripts/tiles.script.ts
> +import { TileTypes } from '../../shared/constants/enums.ts';
discussed

2022-07-01 05:41 UTC, dmutrokot approved these changes

2022-07-01 05:41 UTC, dmutrokot commented on src/pages/Craft/components/ApproveModal.tsx
> +                setTokenApprovals((currentApprovals: boolean[]) => {
how come it can be a `boolean` type?) just put `any`

2022-07-01 05:41 UTC, dmutrokot commented on src/pages/Craft/CraftContext.tsx
> +                    });
fix formatting

2022-07-01 05:41 UTC, dmutrokot commented on src/pages/Craft/CraftContext.tsx
> +    const [tokensApprovals, setTokenApprovals] = useState<object>({
`object` works like stub, do not use it, better for now to use `any` and we will fix it in the future

2022-07-01 07:35 UTC, dudendy approved these changes

2022-07-01 07:36 UTC, merged