Feat/374 card refactoring
orden-gg/fireball pull request #385
Opened 2022-07-29 10:18 UTC by Vladislav94

2022-07-29 13:51 UTC, dmutrokot requested changes

2022-07-29 13:51 UTC, dmutrokot commented on src/components/Gotchi/GotchiCollateral/GotchiCollateral.tsx
no need for whitespace anymore

2022-07-29 13:51 UTC, dmutrokot commented on src/components/Gotchi/GotchiWearablesLine/GotchiWearablesLine.tsx
>  import classNames from 'classnames';
separate please

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCard.tsx
> +import classNames from 'classnames';
sort please

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCard.tsx
> +interface CardItemProps {
component name is `ItemCard`, please name interface respectively

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCard.tsx
> +    type: string;
non optional parameter should not go after optional

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCard.tsx
> +    id?: any;
please add type, as I understand it can be either `number` or `string`, related to `category` also

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/CardContext.tsx
> +
extra

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCard.tsx
> +const CardInner = ({ children, id, category }): JSX.Element => {
missed props interface, please add

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCardHorizontal.tsx
> +import classNames from 'classnames';
wrong order

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCardHorizontal.tsx
> +interface CardItemProps {
please rename interface following component name

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCardHorizontal.tsx
> +    id?: any;
`id` and `category` can be either `number` or `string`

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCardHorizontal.tsx
> +    type: string;
please put above optional parameters

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/ItemCardHorizontal.tsx
> +const CardInner = ({ children, id, category }): JSX.Element => {
missed props interface, and better to name `CardInnerHorizontal` or something like this

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardGroup.tsx
> +    name: string
non-optional at first

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardGroup.tsx
> +    children: Array<JSX.Element> | JSX.Element;
it's just matter of style, but to me you are awaiting single element or array of elements, so please put single first, check other places in the modified files

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardImage.tsx
> +    const [src, setSrc] = useState<string>('');
please separate

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardListing.tsx
> +export function CardListing({ className }: CardListingsProps) {
something not right between actual props and interface props, please check

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardPortalImage.tsx
> +    const renderPortalImage = () => {
missed return type

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardSlot.tsx
> +import { slotStyles } from '../styles';
please separate

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/components/CardSlot.tsx
> +    const slot = ItemUtils.getItemSlotById(id);
should be passed from the higher level and not deciding itself

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/index.ts
> +export { ItemCard } from './ItemCard';
please rework similarly to Gotchi folder with components. So you will have components -> CardBalance -> CardBalance.tsx + styles.ts, styles related to CardBalance. And so on with other components. For ItemCard and ItemCardHorizontal will be better to create containers folders and move appropriate styles into them. For conxtext create `context` folder.

2022-07-29 13:51 UTC, dmutrokot commented on src/components/ItemCard/styles.ts
> +export const styles = makeStyles(theme => createStyles({
all the styles here should be separated respectively to their reworked architecturally components

2022-07-29 13:51 UTC, dmutrokot commented on src/pages/Baazaar/components/BaazaarSortingBody.tsx
> +import { CardBalance, CardImage, CardGroup, CardListing, CardName, CardPortalImage, CardSlot, CardStats, CardTotalPrice, ItemCard, ItemCardHorizontal } from 'components/ItemCard';
please move each import onto newline, there is rule (currently not working) that line length should not be greater than 140

2022-07-29 13:51 UTC, dmutrokot commented on src/pages/Craft/components/CraftItem.tsx
> +    const category = data.category === 'tile' ? Erc1155Categories.Tile : Erc1155Categories.Realm;
please add type

2022-07-29 13:51 UTC, dmutrokot commented on src/pages/Craft/components/Craftbar.tsx
> +            const categoryId = category === 'tile' ? Erc1155Categories.Tile : Erc1155Categories.Realm;
please add type

2022-07-29 13:51 UTC, dmutrokot commented on src/pages/Raffle/components/RaffleItems.tsx
> +import { CardBalance, CardGroup, CardImage, CardListing, CardName, CardPortalImage, CardSlot, CardStats, CardTotalPrice, ItemCard } from 'components/ItemCard';
please separate onto new lines

2022-07-29 13:51 UTC, dmutrokot commented on src/pages/Raffle/components/RaffleItems.tsx
> +import { RaffleItemChance } from './RaffleItemChance';
supposedly styles should go last

2022-07-29 13:51 UTC, dmutrokot commented on src/shared/constants/gotchi.constants.ts
> +export const TRAITS_ICONS: any = {
that is not constants, constants should not rely on something else, please move it somewhere else or create helper

2022-07-29 13:51 UTC, dmutrokot commented on src/utils/installations.utils.ts
> +        const name: string = this.getNameById(id).split(' ')[0].toLowerCase();
please do not use `this` in static classes, use `InstallationsUtils.whateverYouNeed`

2022-07-29 13:51 UTC, dmutrokot commented on src/utils/item.utils.ts
> +    public static getStatsById(id: number, category: string): any {
this method does two things, checking if it's a wearable do some data manipulation and then return stats or just return stats, not hat good tbh. Better to create separate methods, and before calling them check whether it is a wearable or no

2022-07-29 17:26 UTC, dmutrokot requested changes

2022-07-29 17:26 UTC, dmutrokot commented on src/components/ItemCard/components/index.ts
> +export { ItemCard } from '../containers/ItemCard';
containers imports should not be here

2022-07-29 17:26 UTC, dmutrokot commented on src/components/ItemCard/containers/ItemCard.tsx
> +interface ItemCardProps {
whitespace missed

2022-07-29 17:26 UTC, dmutrokot commented on src/components/ItemCard/containers/ItemCard.tsx
> +interface ItemCardInnerProps {
name of component `CardInner` -> `CardInnerProps`

2022-07-29 17:26 UTC, dmutrokot commented on src/components/ItemCard/containers/ItemCardHorizontal.tsx
> +}
whitespace missed

2022-07-29 17:26 UTC, dmutrokot commented on src/components/ItemCard/containers/ItemCardHorizontal.tsx
> +interface ItemCardInnerProps {
please name props interfaces respectively to their components

2022-07-29 17:26 UTC, dmutrokot commented on src/shared/models/trait.model.ts
> +export interface Trait {
interface with one prop in it, it's a little bit redundant:)

2022-07-30 08:17 UTC, Vladislav94 commented on src/components/ItemCard/components/CardImage.tsx
> +        switch (category) {
its complicate to make it in baazaar page, need rework it first

2022-07-30 08:18 UTC, Vladislav94 commented on src/components/ItemCard/components/CardName.tsx
> +    const name: string = ItemUtils.getItemNameById(id);
its complicate to make it in baazaar page, need rework it first

2022-07-30 08:21 UTC, Vladislav94 commented on src/components/ItemCard/components/CardSlot.tsx
> +    const slot = ItemUtils.getItemSlotById(id);
need rework baazaar first

2022-07-30 08:21 UTC, Vladislav94 commented on src/components/ItemCard/components/CardStats.tsx
> +    const isWearable: boolean = category === Erc1155Categories.Wearable;
need rework baazaar first

2022-07-30 08:46 UTC, dmutrokot approved these changes

2022-07-30 08:56 UTC, merged