feat: main page navigation cards, nav panel v2, team section v2
orden-gg/fireball pull request #476
Opened 2022-12-20 08:37 UTC by dudendy

Resolves: #463

2022-12-20 09:15 UTC, skv2rock approved these changes

2022-12-20 12:30 UTC, dmutrokot requested changes

2022-12-20 12:30 UTC, dmutrokot commented on src/data/routes.data.tsx
> +import { Route } from 'shared/models';
`shared` should go first

2022-12-20 12:30 UTC, dmutrokot commented on src/data/routes.data.tsx
> +export const routes: Route[] = [
`routes` - will be better to name `sideNavRoutes` or something like this. The same with model `Route`

2022-12-20 12:30 UTC, dmutrokot commented on src/pages/Main/components/NavigationCards/NavigationCards.tsx
> +import { routes } from 'data/routes.data';
please sort and group imports

2022-12-20 12:30 UTC, dmutrokot commented on src/root/NavPanel/NavPanel.tsx
> +import { Route } from 'shared/models';
should be placed before `data` import

2022-12-26 08:24 UTC, dmutrokot approved these changes

2022-12-26 10:10 UTC, merged