Feat/377 display parcel survey achemica
orden-gg/fireball pull request #480
Opened 2023-01-07 12:37 UTC by skv2rock

2023-01-11 15:49 UTC, dmutrokot requested changes

2023-01-11 15:49 UTC, dmutrokot commented on src/components/Items/Parcel/Parcel.tsx
> +                                    <div className={classNames(classes.boost, key)} key={i}>
`key={i}` you have `key` from `Object.entries`, just use it instead of `index`

2023-01-11 15:49 UTC, dmutrokot commented on src/components/Items/ParcelSurvey/components/ParcelSurveyBar.tsx
> +    avarageSurvey: number;
typo in `avarageSurvey`

2023-01-11 15:49 UTC, dmutrokot commented on src/pages/Baazaar/models/baazaar/parcel-listing.model.ts
> +    listingId: string;
please double check changes in model, something isn't right

2023-01-11 15:49 UTC, dmutrokot commented on src/pages/Baazaar/store/effects/activity-parcels-listings.effect.ts
> +        listingId: listing.listingId,
why you would need to change a mappings?

2023-01-11 15:49 UTC, dmutrokot commented on src/pages/Baazaar/store/effects/parcels-listings.effect.ts
> +            listingId: listing.listingId,
why you would need to change a mappings?

2023-01-11 15:49 UTC, dmutrokot commented on src/shared/models/parcel.model.ts
> +export type ParcelAlchemicaDictionary = {
is it used?

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/alchemica.utils.ts
> +    public static getAvarageSurveyBySize(size: number) {
typo

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/alchemica.utils.ts
> +    public static getAvarageSurveyBySize(size: number) {
please add return type

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/alchemica.utils.ts
> +            (previous: ParcelAlchemica, current: any) => {
no any

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/citadel.utils.ts
> +        switch (id.toString()) {
if `id` is a number just rework `case`'s, to avoid such a weird casting

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/citadel.utils.ts
> +        switch (id.toString()) {
if `id` is a number just rework `case`'s, to avoid such a weird casting

2023-01-11 15:49 UTC, dmutrokot commented on src/utils/graph.utils.ts
> +    public static async getGraphData(url: string, query: string): Promise<AxiosResponse> {
is it used?

2023-01-11 15:49 UTC, dmutrokot commented on subgraph/src/helpers/installation.helper.ts
> +        // eslint-disable-next-line
just add triple equality comparison and remove eslint disable

2023-01-11 15:49 UTC, dmutrokot commented on subgraph/src/helpers/tile.helper.ts
> +        // eslint-disable-next-line
just add triple equality comparison and remove eslint disable

2023-01-13 03:19 UTC, skv2rock commented on src/components/Items/Parcel/Parcel.tsx
> +// import { ERC721Listing } from 'components/Items/ERC721Listing/ERC721Listing';
will be used later

2023-01-13 03:24 UTC, skv2rock commented on src/components/Items/Parcel/Parcel.tsx
> +                className={classNames(classes.item, parcelSize, classes.parcelCard, 'parcel')}
used for add hover, in "survey" styles
<img width="209" alt="image" src="https://user-images.githubusercontent.com/7770528/212229952-176d3e2f-9db0-4496-85ae-9905c0f74df7.png">

2023-01-16 16:00 UTC, dmutrokot requested changes

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Citadel/Citadel.tsx
> +
please remove `console` and blank line

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Items/Parcel/Parcel.tsx
> +                            {Object.entries(boosts).map(([key, value]: (string | number)[]) => {
`(string | number)[]` - that is not a valid type here

2023-01-16 16:00 UTC, dmutrokot commented on src/utils/tiles.utils.ts
> +    public static getTileExist(id: number): boolean {
`getTileExist` -> `getIsTileExists`

2023-01-16 16:00 UTC, dmutrokot commented on src/api/realm.api.ts
> +        return TheGraphCoreApi.getGraphData(GRAPH_FIREBALL_API, queries).then((res: TheGraphResponse<{
that's really weird formatting, please rework

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Items/Parcel/Parcel.tsx
> +                        text={parcel.tokenId || parcel.id}
TODO comment should be left

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Items/Parcel/Parcel.tsx
> +                        <span>#{parcel.tokenId || parcel.id}</span>
TODO comment should be left

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Previews/ParcelPreview/ParcelPreview.tsx
> +                                {parcel.tokenId || parcel.id}
TODO comment should be left

2023-01-16 16:00 UTC, dmutrokot commented on src/components/Login/LoginButton.tsx
> +    address: '0x6865ae680c92Bf047D08Aa7F40CA2Ec5a4f01C5a'
please create a constant for an address

2023-01-17 12:45 UTC, dudendy approved these changes

2023-01-17 12:47 UTC, dmutrokot approved these changes

2023-01-17 12:49 UTC, merged