feat: add recommended wearables
orden-gg/fireball pull request #496
Opened 2023-02-08 08:46 UTC by skv2rock

2023-03-17 08:27 UTC, dmutrokot requested changes

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/Client/store/effects/borrowed-gotchis.effect.ts
> +          .then((FBGotchis: TheGraphBatchData<FBGotchi>[]) => {
please rename `FBGotchis`

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/Client/store/effects/lent-gotchis.effect.ts
> +          .then((FBGotchis: TheGraphBatchData<FBGotchi>[]) => {
please rename `FBGotchis`

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/Client/store/effects/owned-gotchis.effect.ts
> +          .then((FBGotchis: TheGraphBatchData<FBGotchi>[]) => {
please rename `FBGotchis`

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/Client/store/effects/borrowed-gotchis.effect.ts
> +        TheGraphApi.getFBGotchisByIds(ids)
there is an error in console while retrieving all types of client gotchis, that's because you are making the request by ids, however ids can be empty. related to all gotchis effects in the client

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/GotchiPage.tsx
> -  // const [exclusivity, setExclusivity] = useState<CustomAny>({});
please remove if not needed

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/GotchiPage.tsx
> +      .then(([gotchi, FBGotchi]: CustomAny[]) => {
`CustomAny` - you have type here, please specify

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/GotchiPage.tsx
> +                      GotchiUtils.getStakedAmount(gotchi.collateral, Number(gotchi.stakedAmount)).toPrecision(5)
remove `Number` casting

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/GotchiPage.tsx
> +              <GotchiFitSets gotchi={gotchi} className={classes.setsList} />
`GotchiFitSets` takes the whole gotchi object, however using only three properties, please pass those properties instead of the whole object

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/components/GotchiFitWearables/GotchiFitWearable.tsx
> +interface FitWearable extends Wearable {
don't really get it, why would you need to create this interface? as i can see it's for `availableWearables` property, here can be used `Wearable` model though, as there no additional properties are added

2023-03-17 08:27 UTC, dmutrokot commented on src/pages/GotchiPage/components/GotchiFitWearables/GotchiFitWearable.tsx
> +      {availableWearables.map((wearable: CustomAny) => (
`CustomAny` - please replace

2023-03-17 08:27 UTC, dmutrokot commented on src/shared/models/erc-1155-item.model.ts
> +  gotchiId: string
`;` is missing, seems prettier is not working properly in your case, please check

2023-03-17 08:27 UTC, dmutrokot commented on src/shared/models/erc-1155-item.model.ts
> +export interface FBErc1155Item {
:) `FBErc1155Item` -> `Fireball...`, and not really sure whether it can be named as `erc1155`, we can discuss it

2023-03-17 08:27 UTC, dmutrokot commented on src/shared/models/erc-1155-item.model.ts
> +  claimed: IdentityOption[]
better would be to specify here `claimedIdentity` or `claimedOption`, cause just `claimed` stands for an adjective, relates to `unclaimed` also

2023-03-17 08:27 UTC, dmutrokot commented on src/shared/models/gotchi.model.ts
> +  owner: { id: string };
please put nested properties into newline, it's more readable

2023-03-17 08:27 UTC, dmutrokot commented on src/api/common/fb.main.queries.ts
> +export const playerGotchisQuery = (address: string, skip: number): string => {
it's not used anywhere

2023-03-17 08:27 UTC, dmutrokot commented on src/api/common/queries.ts
> +      id
please follow 2 spaces formatting

2023-03-17 08:27 UTC, dmutrokot commented on src/api/thegraph.api.ts
> +  public static getFBGotchisByIds(ids: number[]): Promise<TheGraphBatchData<FBGotchi>[]> {
this method is only used in client effects, consider moving it to client api directory and use graph core api.
and also consider to move query to client queries

2023-03-17 08:27 UTC, dmutrokot commented on src/api/thegraph.api.ts
> +  public static getIventoryByAddress(address: string): Promise<FBErc1155Item[]> {
it is only used in `GotchiPage` component, consider moving it into related directory and use graph core api.

2023-03-20 07:28 UTC, skv2rock commented on src/components/GotchiPreview/components/GotchiIdentity/GotchiIdentity.tsx
they both needthey are both needed

2023-03-20 07:28 UTC, skv2rock commented on src/components/GotchiPreview/components/GotchiIdentity/GotchiIdentity.tsx
they are both needed

2023-03-20 07:51 UTC, skv2rock commented on src/components/GotchiPreview/components/GotchiIdentity/components/IdentityList.tsx
> +      .then((gotchis: GotchiModel[]) => {
interface Gotchi  imported as GotchiModel to avoid conflict with imported component Gotchi

2023-03-20 08:16 UTC, dmutrokot commented on src/components/GotchiPreview/components/GotchiIdentity/GotchiIdentity.tsx
please leave then a comment for these two components, why they are needed and when to use each of them

2023-03-20 08:35 UTC, skv2rock commented on src/components/GotchiPreview/components/GotchiIdentity/GotchiIdentity.tsx
one used for Gotchi component, one for GotchiPreview

2023-03-30 14:57 UTC, dmutrokot requested changes

2023-03-30 14:57 UTC, dmutrokot commented on src/api/common/fireballMain.queries.ts
> +export const playerGotchisQuery = (address: string, skip: number): string => {
please remove this method if it's not used. When we will need then it should be created

2023-03-30 14:57 UTC, dmutrokot commented on src/api/thegraph.api.ts
> +  // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/components/Gotchi/GotchiIdentity/GotchiIdentity.tsx
> +export function GotchiIdentity({ identity }: GotchiLevelProps) {
you are passing here the whole `identity` object, however use only `identity.claimed.length`, please pass only the length

2023-03-30 14:57 UTC, dmutrokot commented on src/components/Gotchi/GotchiPreviewModal/GotchiPreviewModal.tsx
> +            // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/components/GotchiPreview/components/GotchiInfoList/components/GotchiInfoItem/GotchiInfoItem.tsx
> +export function GotchiInfoItem({ isLoaded = true, label, value, title, className }: GotchiInfoItemProps) {
optional parameters should go after required

2023-03-30 14:57 UTC, dmutrokot commented on src/components/ViewInAppButton/ViewInAppButton.tsx
> +export function ViewInAppButton({ target = '_blank', link, children, className }: ViewInAppButtonProps) {
optional parameters should go after required

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/queries/gotchi-batch.query.ts
> +// Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/queries/gotchi-batch.query.ts
> +export const identitiesQuery = (identity: CustomAny): string => {
why `CustomAny`? you can specify type inline if you do not want to create an interface for this

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/borrowed-gotchis.effect.ts
> +          // Should be reworked when gotchi originalOwner will be fixed at FB graph
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/borrowed-gotchis.effect.ts
> +              // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/borrowed-gotchis.effect.ts
> +        if (ids.length > 0) {
logic of this if should be reworked as it does not work correctly. Related to owned and lent gotchis effects

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/lent-gotchis.effect.ts
> +          // Should be reworked when gotchi originalOwner will be fixed at FB graph
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/lent-gotchis.effect.ts
> +              // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/owned-gotchis.effect.ts
> +          // Should be reworked when gotchi originalOwner will be fixed at FB graph
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/Client/store/effects/owned-gotchis.effect.ts
> +              // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/pages/GotchiPage/GotchiPage.tsx
> +        // Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-03-30 14:57 UTC, dmutrokot commented on src/utils/identity.utils.ts
> +// Will be deleted as soon as thegraph updated
please leave a TODO keyword

2023-04-03 04:51 UTC, dmutrokot approved these changes

2023-04-03 08:59 UTC, dudendy approved these changes

2023-04-03 09:32 UTC, merged