delete nav names/add subnav dropdown to gotchis/push up nav container
orden-gg/fireball pull request #510
Opened 2023-02-21 09:49 UTC by npankovich

2023-02-21 22:31 UTC, dmutrokot requested changes

2023-02-21 22:31 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +export interface CustomTooltipProps {
please move this interface into `shared`, due to it's use there

2023-02-23 11:38 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +export interface CustomTooltipProps {
changed/thnxs

2023-02-23 11:39 UTC, dudendy approved these changes

2023-02-23 13:16 UTC, dmutrokot requested changes

2023-02-23 13:16 UTC, dmutrokot commented on src/shared/models/page-nav.model.ts
> +import { CustomTooltipProps } from 'shared/models';
please add whitespace after import

2023-02-23 13:16 UTC, dmutrokot commented on src/shared/models/index.ts
> +export * from './custom-tooltip.model';
please move to related alphabetical imports

2023-02-23 13:16 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +    onMouseLeave={() => onToggleTooltip(false)}>
`>` should be in new line

2023-02-23 13:16 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +
no need for white space here

2023-02-23 13:16 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +      </div>;
please indent properly

2023-02-23 13:16 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +
no need whitespace here, whitespaces needed when they logically separates something,
e.g.
`
const classes = styles();

const [someState, setSomeState] = useState<T>(initialValueOfTypeT);
`

2023-02-23 13:16 UTC, dmutrokot commented on src/components/custom/CustomTooltip.tsx
> +import { CustomTooltipProps } from 'shared/models';
we have following rules about imports : https://www.notion.so/fireball-gg/General-41d2065755d949f78a1438b58acf328c

2023-02-27 09:36 UTC, npankovich commented on src/shared/models/page-nav.model.ts
> +import { CustomTooltipProps } from 'shared/models';
thxs/done

2023-02-27 09:37 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +    onMouseLeave={() => onToggleTooltip(false)}>
thxs/done

2023-02-27 09:37 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +
thxs/done

2023-02-27 09:37 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +      </div>;
thxs/done

2023-02-27 09:37 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +
thxs/done

2023-02-27 09:37 UTC, npankovich commented on src/components/custom/CustomTooltip.tsx
> +import { CustomTooltipProps } from 'shared/models';
thxs/done

2023-03-13 09:25 UTC, dmutrokot requested changes

2023-03-13 09:25 UTC, dmutrokot commented on src/components/CustomDropdown/CustomDropdown.tsx
> +import { useState } from 'react';
do we need this component?

2023-03-13 09:25 UTC, dmutrokot commented on src/shared/models/page-nav.model.ts
> +  dropdown?: boolean;
seems to be redundant property, you can handle how to show/or not show with `isShowSubRoutes`

2023-03-13 09:25 UTC, dmutrokot commented on src/shared/models/custom-tooltip.model.ts
> +export interface CustomTooltipProps {
if `StyledDropdown` from comment above is not needed, please move it back to `CustomTooltip` component

2023-03-13 14:34 UTC, npankovich commented on src/components/CustomDropdown/CustomDropdown.tsx
> +import { useState } from 'react';
no/delete

2023-03-13 14:35 UTC, npankovich commented on src/shared/models/custom-tooltip.model.ts
> +export interface CustomTooltipProps {
done/thnxs

2023-03-13 14:47 UTC, npankovich commented on src/shared/models/page-nav.model.ts
> +  dropdown?: boolean;
done/thnxs

2023-03-14 05:48 UTC, dudendy approved these changes

2023-03-14 05:51 UTC, dudendy requested changes
seems like explorer page is broken in the current branch
https://deploy-preview-510--melodious-elf-4231c5.netlify.app/explorer?sort=mrs&dir=desc
<img width="421" alt="Screenshot 2023-03-14 at 12 51 31" src="https://user-images.githubusercontent.com/42136738/224908411-84a9c8e9-f0b1-4a62-a10d-750e6b11d216.png">

2023-03-14 08:18 UTC, dudendy commented
> seems like explorer page is broken in the current branch https://deploy-preview-510--melodious-elf-4231c5.netlify.app/explorer?sort=mrs&dir=desc <img alt="Screenshot 2023-03-14 at 12 51 31" width="421" src="https://user-images.githubusercontent.com/42136738/224908411-84a9c8e9-f0b1-4a62-a10d-750e6b11d216.png">

resolved by @dmutrokot

2023-03-14 08:19 UTC, dudendy approved these changes

2023-03-14 09:23 UTC, dmutrokot approved these changes

2023-03-14 09:32 UTC, merged