Moved tokenspricescontext logic into store
orden-gg/fireball pull request #562
Opened 2023-03-19 18:35 UTC by npankovich

2023-03-20 09:21 UTC, dmutrokot requested changes

2023-03-20 09:21 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +    const [ghstPrice, ghst]: number[] = await getGhstAndPriceToToken(GHST_CONTRACT, USDC_CONTRACT);
please double check `number` types, I have a doubt that all that types are actually numbers

2023-03-20 09:21 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +  return [ghstPriceToToken, ghst];
please rework here with returning object with needed data instead of array

2023-03-20 09:21 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +      QuickswapApi.getTokenData(FUD_CONTRACT),
please create an interface for `QuickswapApi.getTokenData`, it is not so complicated

2023-03-20 09:21 UTC, dmutrokot commented on src/core/store/tokens-prices/slices/tokens-prices.slice.ts
> +export interface DateTokensPrices {
`DateTokensPrices` - please rename to appropriate state model

2023-03-20 09:21 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +import { setIsPricesLoaded, setTokensPrices } from '../slices/tokens-prices.slice';
please import all from `tokens-prices.slice` and then use it, it will prevent from store mistakes with imports

2023-03-20 15:11 UTC, npankovich commented on src/components/Gotchi/GotchiKinship/GotchiKinshitTooltip.tsx
> +import { TokenTypes } from '../../../shared/constants/enums/enums';
thnxs/done

2023-03-20 15:12 UTC, npankovich commented on src/contexts/BalancesContext.tsx
> +import { useAppDispatch } from '../core/store/hooks';
thnxs/done

2023-03-21 07:59 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +    const [ghstPrice, ghst]: number[] = await getGhstAndPriceToToken(GHST_CONTRACT, USDC_CONTRACT);
thnxs/done

2023-03-21 08:00 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +const getTokenPrice = async (compareToken, compareTokenPrice, targetToken) => {
thnxs/done

2023-03-21 08:01 UTC, npankovich commented on src/shared/models/token-prices.model.ts
> +export type TokenPricesType = {
should be Type ... [key in TokenTypes]: number

2023-03-21 08:06 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +  return [ghstPriceToToken, ghst];
thnxs/done

2023-03-21 10:23 UTC, dmutrokot requested changes

2023-03-21 10:23 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +import * as fromTokensPricesStore from '../slices/tokens-prices.slice';
you are importing here only slices and not the whole store, better naming will be `tokensPricesSlices`

2023-03-21 10:23 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +
no need for whitespace here

2023-03-21 10:23 UTC, dmutrokot commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +const getTokenPrice = async (compareToken: QuickswapToken, compareTokenPrice: number, targetToken: QuickswapToken): Promise<CustomAny> => {
please specify type in return

2023-03-21 10:23 UTC, dmutrokot commented on src/shared/models/token-prices.model.ts
> +export type TokenPricesType = {
however `TokenPricesType` -> `TokenPrices`

2023-03-21 10:23 UTC, dmutrokot commented on src/shared/models/token-prices.model.ts
> +export interface QuickswapToken {
missing whitespace

2023-03-21 10:23 UTC, dmutrokot commented on src/shared/models/token-prices.model.ts
> +  address: string,
seems that changes wasn't prettified, please run prettier

2023-03-21 10:23 UTC, dmutrokot commented on src/shared/models/token-prices.model.ts
> +export interface GhstPriceType {
better naming would be `TokenPrice` or something without linking to `ghst`

2023-03-21 11:41 UTC, npankovich commented on src/shared/models/token-prices.model.ts
> +export type TokenPricesType = {
done

2023-03-21 11:41 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +import * as fromTokensPricesStore from '../slices/tokens-prices.slice';
done

2023-03-21 11:41 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +
done

2023-03-21 11:42 UTC, npankovich commented on src/shared/models/token-prices.model.ts
> +export interface QuickswapToken {
done/thnxs

2023-03-21 11:42 UTC, npankovich commented on src/core/store/tokens-prices/effects/tokens-prices.effect.ts
> +const getTokenPrice = async (compareToken: QuickswapToken, compareTokenPrice: number, targetToken: QuickswapToken): Promise<CustomAny> => {
done/thnxs

2023-03-22 02:22 UTC, skv2rock approved these changes

2023-03-22 06:10 UTC, dudendy approved these changes

2023-03-22 06:11 UTC, merged