573: Fixing average calculation for parcels survey
orden-gg/fireball pull request #574
Opened 2023-04-11 07:10 UTC by skv2rock

resolves #573

2023-04-11 08:41 UTC, dmutrokot requested changes

2023-04-11 08:41 UTC, dmutrokot commented on src/utils/alchemica.utils.ts
> +  public static getIconByName(name: string): ({ width, height }) => JSX.Element {
we already have `getIconByName` in `IconsUtils`, please use that method

2023-04-11 08:49 UTC, skv2rock commented on src/utils/alchemica.utils.ts
> +  public static getIconByName(name: string): ({ width, height }) => JSX.Element {
my bad)

2023-04-11 09:45 UTC, dudendy requested changes
I would suggest making these numbers smaller and replacing the order how the section goes, so `Survey History` should be the last section in the modal

<img width="884" alt="Screenshot 2023-04-11 at 16 41 44" src="https://user-images.githubusercontent.com/42136738/231121548-7851d33d-a000-4de4-9b8d-0ffc6f9c855f.png">

2023-04-12 08:27 UTC, dudendy approved these changes

2023-04-12 10:32 UTC, dmutrokot approved these changes

2023-04-12 10:34 UTC, merged